framework:
    asset_mapper:
        paths:
            - '%kernel.project_dir%/assets'
            - '%kernel.project_dir%/node_modules'
            - '%kernel.project_dir%/vendor/symfony/stimulus-bundle/assets' 

