# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserStatusChecker
            
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                # MODIFICATION ICI : Redirige vers notre route de gestion de redirection
                default_target_path: app_account
                # AJOUT ICI : Force l'utilisation de default_target_path
                always_use_default_target_path: true
                failure_path: app_login
                username_parameter: email
                password_parameter: password

            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/mon-compte, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

